config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : '画像が投稿されています'
    else
      'まだメッセージが投稿されていません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :text, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json{ @latest_messages = @messages.where('id > ?', params[:id]) }
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?) AND id != ?', "%#{params[:keyword]}%", current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, id: 'group', class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label', for: "chat_group_チャットメンバーを追加"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :name, id: 'user-search-field', class: 'chat-group-form__input', placeholder: "追加したいユーザー名を入力してください", type: "text"
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label', for: 'chat_group_チャットメンバー'
    .chat-group-form__field--right
      #chat-group-users
        = current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'shared/sidebar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'messages/notification'
    = yield

app/views/messages/_chat.html.haml
.chat
  .header
    .header__upper
      .header__title
        チャットグループ
      .header__edit
        = link_to edit_group_path(current_user), class: 'header__edit-link' do
          Edit
        -# = link_to "Edit", "#", class: "header__edit-link"
    .header__members
      %p.header__member-title
      %ul.header__members
        %li.member
          - @group.users.each do |user|
            = user.name

  .messages
    %ul
      = render partial: 'message', collection: @messages
  .form
    = form_for [@group, @message] do |f|
      =f.text_field :text, class: 'form__input form__message', placeholder: 'type a message'
      .form__mask
        = f.label :image, class: 'upload-label form__image' do
          = fa_icon "picture-o"
          = f.file_field :image, class: 'hidden', id: 'message_image'
      = f.submit 'Send', class: 'form__submit'

app/views/messages/_message.html.haml
%li.message{ 'data-message-id': "#{message.id}" }
  .message__header
    %p.message__member
      = message.user.name
      %span.message__date
        = message.created_at.to_s(:datetime)
  %p.message__text
    = message.text if message.text.present?
  = image_tag message.image.url, class: 'message__image' if message.image.present?

app/views/messages/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/messages/_sidebar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__menu
      %li
        = link_to new_group_path do
          = fa_icon "edit"
      %li
        = link_to edit_user_path(current_user) do
          = fa_icon "cog"
  .groups
    %ul
      - current_user.groups.each do |group|
        %li.group
          = link_to group_messages_path(group) do
            .group__name
              = group.name
            .group__last-message
              = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render partial: "sidebar"        
  = render partial: "chat", locals: { group: @group, message: @message, messages: @messages }

app/views/messages/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_area :name, class: "chat__group_name chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, class: 'chat-group-form__label'
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        = f.collection_check_boxes :user_ids, User.all, :id, :name
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/shared/_sidebar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__menu
      %li
        = link_to new_group_path do
          = fa_icon "edit"
      %li
        = link_to edit_user_path(current_user) do
          = fa_icon "cog"
  .groups
    %ul
      - current_user.groups.each do |group|
        %li.group
          = link_to group_messages_path(group) do
            .group__name
              = group.name
            .group__last-message
              メッセージはまだありません。

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'